student:
    ID: 3035888888.0
    Name: "FAST-LIO2"

common:
    lid_topic: "/quad1_pcl_render_node/sensor_cloud"
    imu_topic: "/quad_1/imu"
    gt_topic: "/quad_1/lidar_slam/odom"
    last_lidar_time: 1681225930.1732775

preprocess:
    lidar_type: 2               # Livox Avia LiDAR
    feature_extract_en: false
    scan_line: 4
    blind: 0.3

calibration:
    mean_acc_norm: 9.805             # 1 for livox built-in IMU
    orig_odom_freq: 10
    
mapping:
    imu_en: true
    gyr_cov: 0.1
    acc_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    det_range: 29.0
    extrinsic_T: [ -0.0, -0.0, 0.0]
    extrinsic_R: [1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]
    point_filter_num: 4
    filter_size_surf: 0.2
    filter_size_map: 0.4
    cube_side_length: 2000

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
